#!/bin/bash

set -e

if [ $1 == "-fast" ]; then
    OPT=""
else
    OPT="--native"
fi

# compile
echo "Generating interpreter"
scala-cli --power package -f $OPT project.scala stack-lang -M eval -o bin/stki

echo "Genearting compiler"
scala-cli --power package -f $OPT project.scala stack-lang -M compile -o bin/stkc
