#!/bin/bash

set -e

DIR=$(dirname "$0")

retcode=0

error() {
    echo "[error] testing $file failed!"
    retcode=1
}

check() {
    diff $1 $2 || error
}

for item in $DIR/tests/pos/*.stk; do

    if [[ $item == *.ignore ]]; then
        echo "ignore $item"
        continue

    elif [[ -d $item ]]; then
        # directory
        file=$(ls $item/*.stk)
        CHECK=$item/expect.check
        OUT=$item/actual.out
        exe=$item/prog.run
        js=$item/prog.js

    elif [[ -f $item ]] && [[ $item == *.stk ]]; then
        # single source file
        file=$item
        CHECK=$file.check
        OUT=$file.out
        exe=${file%.*}.run
        js=${file%.*}.js

    else
        continue
    fi

    echo "testing $file"

    # create empty check file
    if [ ! -f "$CHECK" ]; then
        touch "$CHECK"
    fi

    # check
    bin/parse $file > /dev/null 2>&1
    bin/type $file > /dev/null 2>&1

    bin/eval $file > $OUT 2>&1
    check $OUT $CHECK

    # Ast interpreter
    # bin/asti $file > $RES2 2>&1
    # check $RES1 $RES2

    # # layout 1
    bin/smc $file -o $exe -layout c1
    $exe > $OUT 2>&1
    check $OUT $CHECK

    # layout 2
    bin/smc $file -o $exe -layout c2
    $exe > $OUT 2>&1
    check $OUT $CHECK

    # TODO fast linux
    # bin/rmc $file -o $exe -p linux-x86-reg
    # $exe > $OUT 2>&1
    # check $OUT $CHECK

    # JavaScript
    bin/jsc $file -o $js -p js
    node $js > $OUT 2>&1
    check $OUT $CHECK
done

# neg tests
echo
echo "Running negative tests"
echo
scala-cli project.scala stack-lang -M negTest
if [[ $? != 0 ]]; then
  retcode=1
fi

echo $retcode
exit $retcode
