#!/bin/bash

DIR=$(dirname "$0")

# run tests
RES1=$DIR/tests/pos/int.txt
RES2=$DIR/tests/pos/exe.txt
RES3=$DIR/tests/pos/js.txt

retcode=0

check() {
    diff $1 $2
    if [[ $? != 0 ]]; then
        echo "[error] testing $file failed!"
        retcode=1
    fi
}

for file in $DIR/tests/pos/*.stk; do
    echo "testing $file"
    exe=${file%.*}.run
    js=${file%.*}.js
    bin/stki $file > $RES1 2>&1

    # # layout 1
    bin/stkc $file -o $exe -p linux-x86 -layout c1
    $exe > $RES2
    check $RES1 $RES2

    # layout 2
    bin/stkc $file -o $exe -p linux-x86 -layout c2
    $exe > $RES2 2>&1
    check $RES1 $RES2

    # layout 3
    bin/stkc $file -o $exe -p linux-x86 -layout c3
    $exe > $RES2 2>&1
    check $RES1 $RES2

    # fast linux
    bin/stkc $file -o $exe -p linux-x86-fast
    $exe > $RES2 2>&1
    check $RES1 $RES2

    # JavaScript
    bin/stkc $file -o $js -p js
    node $js > $RES3 2>&1
    check $RES1 $RES3

    # JavaScript optimized
    bin/stkc $file -o $js -p js-opt
    node $js > $RES3 2>&1
    check $RES1 $RES3
done

rm $RES1
rm $RES2
rm $RES3

# neg tests
echo
echo "Running negative tests"
echo
scala-cli project.scala stack-lang -M negTest
if [[ $? != 0 ]]; then
  retcode=1
fi

echo $retcode
exit $retcode
