#!/bin/env bash

DIR=$(dirname "$0")

INTERPRETER=$DIR/Interpreter.scala
COMPILER=$DIR/Compiler.scala

# compile
echo "Compiling $INTERPRETER"
scala-cli compile $INTERPRETER

echo "Compiling $COMPILER"
scala-cli compile $COMPILER

# run tests
RES1=$DIR/tests/int.txt
RES2=$DIR/tests/exe.txt
RES3=$DIR/tests/js.txt


retcode=0

check() {
    diff $1 $2
    if [[ $? != 0 ]]; then
        echo "[error] testing $file failed!"
        retcode=1
    fi
}

for file in $DIR/tests/*.stk; do
    echo "testing $file"
    exe=${file%.*}.run
    js=${file%.*}.js
    scala-cli $INTERPRETER -- $file > $RES1

    # # layout 1
    scala-cli $COMPILER -- $file -o $exe -p linux-x86 -layout c1
    $exe > $RES2
    check $RES1 $RES2

    # layout 2
    scala-cli $COMPILER -- $file -o $exe -p linux-x86 -layout c2
    $exe > $RES2
    check $RES1 $RES2

    # layout 3
    scala-cli $COMPILER -- $file -o $exe -p linux-x86 -layout c3
    $exe > $RES2
    check $RES1 $RES2

    # JavaScript
    scala-cli $COMPILER -- $file -o $js -p js
    node $js > $RES3
    check $RES1 $RES3

    # JavaScript optimized
    scala-cli $COMPILER -- $file -o $js -p js-opt
    node $js > $RES3
    check $RES1 $RES3
done

rm $RES1
rm $RES2
rm $RES3
echo $retcode
exit $retcode
