name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main

      - name: stack lang interpreter
        run: |
          for file in stack-lang/tests/*.stk; do
            echo "Interpreting $file"
            scala-cli stack-lang/interpreter.scala -- $file
          done

      - name: stack lang compiler
        run: |
          for file in stack-lang/tests/*.stk; do
            echo "Compiling $file"
            scala-cli stack-lang/compiler.scala -- $file
            exe=${file%.*}
            echo "Running $exe"
            $exe
          done
